import Head from "next/head";
import Header from "@/components/Header";
import Center from "@/components/Center";
import styled from "styled-components";

import LogoAndSearch from "@/components/LogoAndSearch";
import Banner from "@/components/Banner";
import TodayItem from "@/components/TodayItem";
import Products from "@/components/Products";

import Community from "@/components/Community";
import Youtube from "@/components/Youtube";
import AdArea from "@/components/AdArea";
import PopularBooks from "@/components/PopularBooks";
// import Market from "@/components/Market";
import MobiletOtc from "@/components/MobiletOtc";
import WinwinMarket from "@/components/WinwinMarket";
import TodakAndNews from "@/components/TodakAndNews";
import AdAndInterview from "@/components/AdAndInterview";
import Linktree from "@/components/MobickLinktree";

import Footer from "@/components/Footer";
// import NewsSection from "@/components/NewsSection";
// import VerificationSection from "@/components/VerificationSection";

const StyledDiv = styled.div`
  display: flex;
  justify-content: center;
  align-items: center;
`;

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Center>
        <LogoAndSearch />
        <Banner />
        <TodayItem />
        <Products />
        <Youtube />
        <PopularBooks />
        {/* <MultiSection /> */}
        <Community />
        <MobiletOtc />
        <WinwinMarket />
        <TodakAndNews />
        <AdAndInterview />
        {/* <Market /> */}
        {/* <NewsSection /> */}
        <AdArea />
        <Linktree />
        {/* <VerificationSection /> */}
        <Footer />
      </Center>
    </>
  );
}
